name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: set api key
        run: echo API_KEY=${{ secrets.CMS_KEY }} > .env

      - name: set api posts endpoint
        run: echo API_POSTS_ENDPOINT=${{ secrets.API_POSTS_ENDPOINT }} >> .env

      - name: set api clubs endpoint
        run: echo API_CLUBS_ENDPOINT=${{ secrets.API_CLUBS_ENDPOINT }} >> .env

      - name: set gtm id
        run: echo GTM_ID=${{ secrets.GTM_ID }} >> .env

      - name: install
        run: npm ci

#      - name: test
#        run: npm test

      - name: build
        run: npm run build

      - name: export
        run: npm run export

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
